apiVersion: v1
kind: Service
metadata:
  name: {{.Value.db.service.name}}
spec:
  selector:
    app: mongo
  ports:
  - port: {{.Value.db.service.port}}
    targetPort: {{.Value.db.service.port}}
  clusterIP: None