apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox-secret
  name: busybox-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-secret
  strategy: {}
  template:
    metadata:
      labels:
        app: busybox-secret
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                key: USERNAME
                name: velotio-secret
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: PASSWORD
                name: velotio-secret

status: {}
