apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: velotio-ajay
  labels: 
    app: velotio
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    resources: {}